version: 2.1

latest: &latest
  pattern: "^1.18.*-erlang-27.*$"

tags: &tags
  [
    1.18.3-erlang-27.3.3-alpine-3.21.3,
    1.17.3-erlang-27.3.3-alpine-3.21.3,
    1.16.3-erlang-26.2.5.11-alpine-3.21.3,
    1.15.8-erlang-26.2.5.11-alpine-3.21.3
  ]

jobs:
  check-license:
    docker:
      - image: fsfe/reuse:latest
    steps:
      - checkout
      - run: reuse lint

  build-test:
    parameters:
      tag:
        type: string
    docker:
      - image: hexpm/elixir:<< parameters.tag >>
    working_directory: ~/repo
    environment:
      LC_ALL: C.UTF-8
    steps:
      - run:
          name: Install system dependencies
          command: apk add --no-cache build-base
      - checkout
      - run:
          name: Install hex and rebar
          command: |
            mix local.hex --force
            mix local.rebar --force
      - restore_cache:
          keys:
            - v1-mix-cache-<< parameters.tag >>-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: MIX_ENV=test mix compile --warnings-as-errors
      - run: mix test
      - run: cd examples/wifi_demo && mix deps.get && mix test && mix docs
      - when:
          condition:
            matches: { <<: *latest, value: << parameters.tag >> }
          steps:
            - run: mix format --check-formatted
            - run: mix deps.unlock --check-unused
            - run: mix docs
            - run: mix hex.build
            - run: mix credo -a --strict
            - run: mix dialyzer
      - save_cache:
          key: v1-mix-cache-<< parameters.tag >>-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps

workflows:
  checks:
    jobs:
      - check-license:
          filters:
            tags:
              only: /.*/
      - build-test:
          name: << matrix.tag >>
          matrix:
            parameters:
              tag: *tags
          filters:
            tags:
              only: /.*/
